name: Node.js CI

on: [push]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./server
        run: npm i
      - name: Run tests
        working-directory: ./server
        run: npm test
  build-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./reporter
        run: npm i
      - name: Compile
        working-directory: ./reporter
        run: npm run build
